name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Available OS Images:
        # https://github.com/actions/runner-images/#available-images
        #
        # Allow Python pre-releases:
        # https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#allow-pre-releases
        # See "allow-prereleases: true" below.
        os: [ubuntu-latest]
        python:
          # Python versions (CPython):
          # https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
        include:
          - os: windows-latest
            python: 3.12
          - os: ubuntu-20.04
            python: 3.6
          - os: ubuntu-20.04
            python: 3.5


    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          allow-prereleases: true
          python-version: ${{ matrix.python }}
      - name: Run tests
        run: python runtests.py --current --verbose

  # Test Python 2.7 with python2.7 package of Ubuntu 22.04
  test_python27:
    name: 'Test Python 2.7'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Python 2.7
        run: |
          sudo apt-get update
          sudo apt-get -yq install python2.7 python2.7-dev
      - name: Display the Python version
        run: python2.7 -VV
      - name: Run tests
        run: python2.7 runtests.py --current --verbose
